### PR TITLE
Issue 61 Fix buffer position issue during createPdu

### PR DESCRIPTION
**Pull request by Serubin**
See #61 for description

### CODE REVIEW

**Comment by leif81** [comment]
Thankyou @Serubin . Nice catch.

The fix here looks like it will indeed fix the issue with `BehaviorProducerUDP`, but I'm wondering if the rewind may cause issues anywhere else. e.g. maybe in `ConcatenatedDisPdus`.

@mcgredonps do you recall what the use case for `useCopies` in `BehaviourProducerUDP` was? I don't think I've ever found myself in a situation where I wanted a copy of PDU (why, to modify it?)

Would anyone object if we got rid of `useCopies` instead?

**Comment by Serubin** [comment]
I don't see a use for useCopies (though it's set to default true). However, the buffer should likely be reset regardless for consistency between functions.

**Comment by leif81** [comment]
Ok, are you able to give it a try? Feel free to remove the `useCopies` member and any references to it on this branch.

**Comment by Serubin** [comment]
I'm unsure how to test `ConcatenatedDisPdus` but I can absolutely remove `useCopies`

**Comment by leif81** [comment]
@Serubin Ok sounds good.

**Comment by Serubin** [comment]
This has not fallen off my radar - I just haven't have a chance to get to it. Should get to it over the next week.

**Comment by Serubin** [comment]
I've removed `useCopies` and the buffer reset stuff looks good on ConcatPdus

**Comment by leif81** [comment]
thank-you @Serubin !

**Pull request merged**
