### PR TITLE
Improve support for dis radio handling

### PR DESCRIPTION
**Pull request by leif81**
With these fixes and enhancements open-dis can now be used as a library to implement a basic dis radio application that sends and/or receives audio with Signal and Transmitter PDU's.

Please see the commits in this PR for breakdown of changes.

### CODE REVIEW

**Comment by mcgredonps** [comment]
The generator code is not extremely difficult, but it has a lot of details.

**Comment by leif81** [comment]
Ok, I suspect I will have to learn more about the generator to avoid some changes like these from getting overwritten :smile:

**Comment by mcgredonps** [comment]
The radio comms is cool. I really want to see an implementation in Javascript. With HMTL 5 you can access the mic on the computer hosting the web page, so it should be possible to have an entirely web-based radio comms component. 

Pushing the radio packets over a websocket has well known pathologies but I think it will mostly work on LANs, and if not it should be possible to shove them out over WebRTC.

**Comment by leif81** [comment]
Exciting times for sure. If you have any luck with that I'd be very curious. It's been on my mind lately too.

**Pull request merged**
