### PR TITLE
Issue #31

### PR DESCRIPTION
**Pull request by camejia**
Bug in deadreckoning.utils Matrix mult.

### CODE REVIEW

**Comment by leif81** [comment]
My matrix math is a little rusty, but this looks reasonable to me.

@mcgredonps what do you think?

**Comment by camejia** [comment]
I should have put into my commit or pull request comments: the problem is that the inner loop should be over the number of columns of the left matrix (or number of rows of the right matrix); instead the inner loop was looping over the number of columns of the right matrix.

Also, after submitting a pull request, I see that there is some sort of continuous-integration check.  Is there a way to add my new JUnit test case to this CI?

This is the first time I've contributed to an open source project (yay!) and I'm not very familiar with GitHub, so I appreciate you guys helping to get me up to speed so I can continue to contribute!

**Comment by leif81** [comment]
Ok thank you Chris!

The way you've added the unit test is perfect actually. The travis CI build passed for this PR which is perfect, it means your test ran and passed 👍 You can see it in the output of the job here:

https://travis-ci.org/open-dis/open-dis-java/builds/227470895#L787
```
Running edu.nps.moves.deadreckoning.utils.MatrixTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
```

**Comment by mcgredonps** [comment]
Looks OK. A student wrote that DR code many years ago. It's kinda bad that he used his own implementation of Java matrices, and it would be better to use one of the well-known libraries, perhaps from Apache Commons, but that would also imply a fairly large rewrite of the DR code. Nice that there's now test code included.

Slightly surprising that Java doesn't have its own matrix arithmetic package.

On the Ant side there's a step that can run the JUnit tests. There's something similar on the maven side but I haven't looked into running it there.

**Comment by mcgredonps** [comment]
BTW, I'm doing an "electronic book" on DIS, and an extremely early draft is at https://github.com/open-dis/DISTutorial . Any feedback is welcome.

**Comment by camejia** [comment]
Thanks guys.  I plan to work on rewriting the DR code, to use Apache Commons Math, and follow the implementation in the Towers & Hines paper.  All while maintaining the same interfaces in the current Open-DIS DR code.  Hopefully this is agreeable to you both, but if you have further suggestions please let me know.

The "electronic book" is a great idea, and is something I may contribute to in the future.  I do have a detailed question, not currently answered in the "electronic book", that maybe you can help answer, or connect me with someone who can answer.  For the body-centered Dead Reckoning algorithms, is the acceleration: (1) the acceleration in body coordinates, or (2) the time derivative of the velocity in body coordinates?  The Towers & Hines paper explains the difference, and assumes that the PDU contains (2).  However, my reading of the current IEEE Std leads me to believe that the PDU contains (1).  It is possible that the Towers & Hines paper is just not up to with the latest IEEE Std in this area.  Any leads you have on tracking down a definitive answer would be appreciated.  Otherwise, I'll just make an assumption and document it in the code.

**Comment by mcgredonps** [comment]
Where abouts in the Hines paper? Is the classic definition of acceleration that it is the time derivative of the velocity, or is there a difference here?

A good place to ask questions like this is the DIS protocol support group (https://www.sisostds.org/StandardsActivities/SupportGroups/DISRPRFOMPSG.aspx, https://discussions.sisostds.org/index.htm?A0=SAC-PSG-DIS-RPRFOM )

**Comment by mcgredonps** [comment]
I'd love to have someone write the DR sections of the DIS discussion manual, btw. There's a lot to write, I'm not all that up to speed on it, and it would be really useful to people. 

The whole manual may get some drive-by readers from the gamer industry.

**Comment by camejia** [comment]
From page 441 of the Towers & Hines paper: "Note: The quantity A_b, which is the time derivative of V_b, is not generally equal to the entity acceleration expressed in body coordinates (a_b)."

I noticed the following in IEEE Std 1278.1-2012 paragraph 1.6.3.3:
"Linear velocity and acceleration vectors are transmitted in either world or entity coordinates, depending on the dead reckoning algorithm in use. For linear velocity, the same vector (i.e., the same magnitude and direction from a world view) is represented with either method, only the coordinate axes for defining it are different. For acceleration, however, the centripetal component is removed when converting from world coordinates into body coordinates. For example, an entity turning in a circular path with constant speed has a nonzero, purely centripetal acceleration in world coordinates, but zero acceleration in entity coordinates."

Which leads me to believe that the field should contain A_b, and not a_b.  I'll check out the DIS protocol support group and see if there is any further discussion of this issue.  I'd love to help with the DR sections of the DIS discussion manual, but I'm not sure how much time commitment I'll be able to make.  I think that first I'll work on some code updates to address the Issues I've entered, but I can't commit to how fast I'll be able to work on those either...

**Comment by mcgredonps** [comment]
Woof. I didn't realize that was what the protocol designers were up to.

**Pull request merged**
