### PR TITLE
Fix duplicate attributes from SimulationManagementFamilyPdu

### PR DESCRIPTION
**Pull request by tzneal**
Remove the duplicate originating/receiving IDs as they are already part of SimulationManagementFamilyPdu

### CODE REVIEW

**Comment by leif81** [comment]
Maybe those duplicate fields should be removed from all pdu's that inherit from `SimulationManagementFamilyPdu`?

e.g. `CreateEntityPdu`, `RemoveEntityPdu`, `StopFreezePdu`, `AcknowledgePdu`, `ActionRequestPdu`, `ActionResponsePdu`, should have it removed to.

**Comment by mcgredonps** [comment]
There's a SimulationManagementHeader object defined in the standard, which is just the regular PDU header plus the two identifier fields. It's defined earlier in the XML file. I don't think it's worthwhile to reuse that here, since it would make for a special case in the inheritance chain. Better to just remove the duplicate fields in the subclasses.

**Comment by tzneal** [comment]
I cleaned up the other sim family PDUs and also removed a duplicate PDU that I noticed.

**Comment by leif81** [comment]
Nice. Looks good to me.

**Pull request merged**
