### PR TITLE
Transmitter PDU update

### PR DESCRIPTION
**Pull request by fo-ifad**
Added classes to handle Modulation parameters for Radio System Type 6…and Type 8 (according to doc "Enumeration and Bit Encoded Values for Use with Protocols for Distributed Interactive Simulation Applications" section 9.1.7.1 and 9.1.7.2 respectively), edited spherical antenna patterns to include missing attributes(according to doc IEEE Std 1278.1-1995 section 5.2.4.3) and edited the Transmitter PDU to use these

### CODE REVIEW

**Comment by leif81** [comment]
Thank-you @fo-ifad !
It'll likely be sometime next week when I can take a closer look.

**Comment by leif81** [comment]
@fo-ifad you add a unit test with sample pdu?

**Comment by fo-ifad** [comment]
I am not sure I am able to generate a Transmitter PDU from VR-Forces, I have tried but no success

**Comment by leif81** [comment]
Ok. Is your use case to receive and parse a Transmitter PDU or create and sent one? I had made the assumption it was the former, but if it's the later then I understand you may not have a sample PDU.

**Comment by fo-ifad** [comment]
The case is both send and receive transmitter PDU, however it was my understanding that the unit tests are to try out open-dis with PDU generated from other programs that doesn't use open-dis(or at least i think it doesn't)

Also how often is a release made for open-dis and dis-enumerations?

**Comment by leif81** [comment]
Yes ideally the unit test for the `unmarshal` method we test with a PDU sent by another program.

I've been planning to cut a open-dis-java 5.1 release really soon actually. Likely this week or next. The dis-enumerations dependency hasn't changed in a while so it'll be unchanged in 5.1 release.

**Comment by fo-ifad** [comment]
That sounds great, i do have 3 more branches with patches, waiting, which could be very nice to get in this new version, if possible

**Comment by leif81** [comment]
@fo-ifad ok good to know more is coming.

I am uneasy about merging this large change without a unit test. Is there some other system that can send a Transmitter Pdu containing the modulation parameters and spherical attenna patterns that are being added in this change?

**Pull request closed without merging**
