### PR TITLE
Fixup Set Data Pdu

### PR DESCRIPTION
**Pull request by leif81**
Lately I've been experimenting with the VBS 3.8 Gateway DIS interface. I got excited when I noticed it supported sending VBS script commands via Set Data Pdu's and then responses back in Data Pdu's. I've never used these Pdu's before so it didn't surprise me the following fixes were required to make OpenDIS send valid PDU's (verified with Wireshark).

Some of these fixes may be more appropriate in xmlpg (?), but I'm still not comfortable enough with that process yet. Worst case this at least adds a couple more unit tests to catch regressions in case xmlpg is re-run and blows away changes to the PDU's.

P.S. I haven't forgotten about cutting an open-dis-java 5.0 release, it's still on my radar. After this PR is merged I'd like to find some time to focus on doing that.

### CODE REVIEW

**Comment by IanMayo** [comment]
+1, nice coding Leif.

**Comment by leif81** [comment]
Thanks @IanMayo 

@mcgredonps what do you think?

**Comment by mcgredonps** [comment]
Looks good. Do you have a copy of the DIS 7 standard? It tends to go into more detail about what they "really" mean, even for the pre-DIS 7 things.

Don Brutzman's web page is pretty horribly out of date on DIS and you probably shouldn't be relying on it. I've been trying to get him to take it down for a while.

**Comment by leif81** [comment]
Ah good to know! I don't have a copy of the DIS 7 standard, maybe I should find one.

**Comment by mcgredonps** [comment]
mcgredo@nps.edu<mailto:mcgredo@nps.edu>

Drop me a line.

On Jul 25, 2016, at 11:20 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah good to know! I don't have a copy of the DIS 7 standard, maybe I should find one.

**Pull request merged**
